# Generated by Django 5.0.4 on 2025-04-16 14:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subplans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sets_reps', models.CharField(max_length=255)),
                ('intensity', models.CharField(max_length=255)),
                ('tempo', models.CharField(blank=True, max_length=255, null=True)),
                ('rest', models.CharField(max_length=255)),
                ('video_url', models.URLField()),
                ('day', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolutions', to='programs.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='ReadyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subplans.subplan')),
            ],
        ),
        migrations.CreateModel(
            name='ReadyExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sets_reps', models.CharField(max_length=255)),
                ('intensity', models.CharField(max_length=255)),
                ('tempo', models.CharField(max_length=255)),
                ('rest', models.CharField(max_length=255)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('day', models.CharField(max_length=50)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='programs.readyprogram')),
            ],
        ),
        migrations.CreateModel(
            name='TrainerStudentProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(limit_choices_to={'is_trainer': False}, on_delete=django.db.models.deletion.CASCADE, related_name='student_programs', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(limit_choices_to={'is_trainer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_programs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='programs.trainerstudentprogram'),
        ),
    ]
