# Generated by Django 5.0.4 on 2025-04-18 08:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sets_reps', models.CharField(max_length=255)),
                ('intensity', models.CharField(max_length=255)),
                ('tempo', models.CharField(blank=True, max_length=255, null=True)),
                ('rest', models.CharField(max_length=255)),
                ('video_url', models.URLField()),
                ('day', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReadyExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sets_reps', models.CharField(max_length=255)),
                ('intensity', models.CharField(max_length=255)),
                ('tempo', models.CharField(max_length=255)),
                ('rest', models.CharField(max_length=255)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('day', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReadyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerStudentProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolutions', to='programs.exercise')),
            ],
        ),
    ]
