version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      ./production.env
    volumes:
      - ./backend:/app
    command: uvicorn backend.asgi:application --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8080:80"

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file:
      - ./production.env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: