FROM python:3.11-alpine

RUN apk add --no-cache gcc musl-dev libffi-dev python3-dev build-base postgresql-dev

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "backend.asgi:application", "--host", "0.0.0.0", "--port", "8000"]