# Generated by Django 5.0.4 on 2025-04-18 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subplans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subplanfeature',
            name='subplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subplans.subplan'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='subplan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subplans.subplan'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
